from colorama import Fore, Back, Style
print(Fore.BLUE+50*"=")
print(Fore.MAGENTA+"COLORES CON COLORAMA")
print(Fore.BLUE+50*"=")
print(Back.LIGHTBLACK_EX + "Cambiando el fondo")
print(Back.RESET+50*"=")
print(Fore.BLUE+"Aplicando color azul al texto")
print(50*"=")
print(Fore.GREEN + "Un ejemplo de frase de color verde")
print(Fore.RED + "Cambiando a frase de color rojo")
print("Aplica el color que quieras en cualquiera de los textos")
print(Fore.YELLOW +50*"=")
print("Finalizando...")
print(50*"=")
print(Style.RESET_ALL,end="")
print("Hemos vuelto a los colores por defecto \n.....FIN")
